### ISSUE TITLE
Fixing Row 103

### ISSUE THREAD

**Issue by Tpavdrceelen** [course-dprep/IMDb-ActorInfluence#32]
Seperating column 'genre' is not working, chance the code so it only looks at the rows that have multiple rows to improve speed.

**Comment by Metteswanenberg** [comment]
The problem is not in row 103 anymore, it is about 114, including ```{r}
cdata1 <- rename(cdata1, tconst = knownForTitles)
```.

**Comment by srosh2000** [comment]
M not sure what the problem is with 114.. it runs correctly. However, the code where you use separate_rows to parse the genre column can be made more efficient using data.table package as it is more memory efficient and faster for handling large data sets.

Here is a more optimised code: 

```
library(data.table)

# Convert to data.table
setDT(cdata1)
setDT(cdata3)

# Split 'knownForTitles' into separate rows
cdata1 <- cdata1[, .(primaryName, primaryProfession, tconst = unlist(strsplit(knownForTitles, ","))), by = .I]

# Split 'genres' into separate rows
cdata3 <- cdata3[, .(tconst, primaryTitle, startYear, genre = unlist(strsplit(genres, ","))), by = .I]
```

Lemme know if this helps
